In [1]:
from google.colab import drive
drive.mount('/content/drive')
!pip install "drive/MyDrive/Master Data Science/TFM/GITHUB/modelado_multidimensional_engagement-0.1.0-py3-none-any.whl"

Mounted at /content/drive
Processing ./drive/MyDrive/Master Data Science/TFM/GITHUB/modelado_multidimensional_engagement-0.1.0-py3-none-any.whl
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from modelado-multidimensional-engagement==0.1.0) (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from modelado-multidimensional-engagement==0.1.0) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from modelado-multidimensional-engagement==0.1.0) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from modelado-multidimensional-engagement==0.1.0) (1.16.3)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (from modelado-multidimensional-engagement==0.1.0) (18.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->modelado-multidimensional-engagement==0.1.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->modelado-multidimensional-engagement==0.1.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->modelado-multidimensional-engagement==0.1.0) (2026.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->modelado-multidimensional-engagement==0.1.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->modelado-multidimensional-engagement==0.1.0) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->modelado-multidimensional-engagement==0.1.0) (1.17.0)
Installing collected packages: modelado-multidimensional-engagement
Successfully installed modelado-multidimensional-engagement-0.1.0

In [2]:
import pandas as pd
import os

from src.preprocessing.general import GeneralPreprocessor
from src.preprocessing.user_based import UserBasedPreprocessor
from src.preprocessing.time_based import TimeBasedPreprocessor
from src import config

In [3]:
config.CATEGORY_CODES

['electronics.video.tv',
 'computers.components.memory',
 'computers.components.motherboard',
 'appliances.kitchen.juicer']

In [4]:
config.WORKPATH

'drive/MyDrive/Master Data Science/TFM/GITHUB'

In [5]:
general_preprocessor = GeneralPreprocessor()
user_based_preprocessor = UserBasedPreprocessor()
time_based_preprocessor = TimeBasedPreprocessor()

In [6]:
general_metrics = general_preprocessor.process(train_eval="training_201911")
user_based_metrics = user_based_preprocessor.process(train_eval="training_201911")
time_based_metrics = time_based_preprocessor.process(train_eval="training_201911")

  0%|          | 0/4 [00:00<?, ?it/s]

Procesando: electronics.video.tv

 25%|██▌       | 1/4 [02:07<06:22, 127.55s/it]

Procesando: computers.components.memory

 50%|█████     | 2/4 [02:16<01:55, 57.56s/it]

Procesando: computers.components.motherboard

 75%|███████▌  | 3/4 [02:23<00:34, 34.87s/it]

Procesando: appliances.kitchen.juicer

100%|██████████| 4/4 [02:30<00:00, 37.61s/it]

Resultados guardados en: drive/MyDrive/Master Data Science/TFM/GITHUB/processed/training_201911/aggregated_generic.parquet

  0%|          | 0/4 [00:00<?, ?it/s]

Procesando: electronics.video.tv

 25%|██▌       | 1/4 [02:03<06:10, 123.59s/it]

Procesando: computers.components.memory

 50%|█████     | 2/4 [02:09<01:49, 54.52s/it]

Procesando: computers.components.motherboard

 75%|███████▌  | 3/4 [02:15<00:32, 32.35s/it]

Procesando: appliances.kitchen.juicer

100%|██████████| 4/4 [02:20<00:00, 35.06s/it]

Resultados guardados en: drive/MyDrive/Master Data Science/TFM/GITHUB/processed/training_201911/user_based_metrics.parquet

  0%|          | 0/4 [00:00<?, ?it/s]

Procesando: electronics.video.tv

 25%|██▌       | 1/4 [02:03<06:09, 123.28s/it]

Procesando: computers.components.memory

 50%|█████     | 2/4 [02:09<01:48, 54.35s/it]

Procesando: computers.components.motherboard

 75%|███████▌  | 3/4 [02:15<00:32, 32.27s/it]

Procesando: appliances.kitchen.juicer

100%|██████████| 4/4 [02:19<00:00, 34.95s/it]

Resultados guardados en: drive/MyDrive/Master Data Science/TFM/GITHUB/processed/training_201911/time_based_metrics.parquet

In [7]:
general_metrics

,category_code,visits,users,clicks,click_depth,dwell_time_avg,active_days,return_rate,dwelltime_l
0,electronics.video.tv,508941,260719,1190621,2.341212,334.690761,1.496381,1.952071,653.339261
1,computers.components.memory,25687,12212,50017,1.948309,134.618795,1.510481,2.103423,283.160252
2,computers.components.motherboard,24796,10435,48204,1.944651,331.083037,1.578438,2.376234,786.730713
3,appliances.kitchen.juicer,18493,12939,41810,2.261834,184.385983,1.216477,1.429245,263.532730

In [8]:
user_based_metrics

,category_code,Tourist_users,Tourist_visits,Interested_users,Interested_visits,Average_users,Average_visits,Active_users,Active_visits,VIP_users,...,Tourist_return_rate,Interested_return_rate,Average_return_rate,Active_return_rate,VIP_return_rate,Tourist_dwelltime_l,Interested_dwelltime_l,Average_dwelltime_l,Active_dwelltime_l,VIP_dwelltime_l
0,electronics.video.tv,193113,223650,60013,198515,6484,61277,1009,20882,100,...,1.158135,3.307867,9.450494,20.695738,46.17,177.246436,1484.064419,4174.165793,8561.593657,113422.71
1,computers.components.memory,9163,11703,2634,9478,345,3180,66,1202,4,...,1.277202,3.598330,9.217391,18.212121,31.00,99.818509,527.283979,2762.672464,2952.742424,1611.75
2,computers.components.motherboard,7737,10095,2247,9008,350,3631,99,1982,2,...,1.304769,4.008901,10.374286,20.020202,40.00,116.282538,2201.036493,5463.734286,4413.797980,7427.50
3,appliances.kitchen.juicer,11127,12321,1721,5283,83,729,7,117,1,...,1.107307,3.069727,8.783133,16.714286,43.00,157.038914,842.167345,2232.493976,2166.571429,12645.00

In [9]:
time_based_metrics

,category_code,users,visits,clicks,click_depth,dwell_time_avg,return_rate,dwelltime_l
0,electronics.video.tv,0.609968,0.635513,0.621812,0.478314,0.525364,0.527163,0.552385
1,computers.components.memory,0.647557,0.694784,0.682868,0.482831,0.441739,0.553362,0.495039
2,computers.components.motherboard,0.643746,0.691734,0.679466,0.482706,0.565750,0.553933,0.618009
3,appliances.kitchen.juicer,0.605822,0.618978,0.594451,0.467457,0.440700,0.513854,0.454404

In [10]:
general_metrics_dic = general_preprocessor.process(train_eval="evaluation_201912")
user_based_metrics_dic = user_based_preprocessor.process(train_eval="evaluation_201912")
time_based_metrics_dic = time_based_preprocessor.process(train_eval="evaluation_201912")

  0%|          | 0/4 [00:00<?, ?it/s]

Procesando: electronics.video.tv

 25%|██▌       | 1/4 [00:44<02:13, 44.37s/it]

Procesando: computers.components.memory

 50%|█████     | 2/4 [00:48<00:41, 20.64s/it]

Procesando: computers.components.motherboard

 75%|███████▌  | 3/4 [00:53<00:13, 13.67s/it]

Procesando: appliances.kitchen.juicer

100%|██████████| 4/4 [01:10<00:00, 17.68s/it]

Resultados guardados en: drive/MyDrive/Master Data Science/TFM/GITHUB/processed/evaluation_201912/aggregated_generic.parquet

  0%|          | 0/4 [00:00<?, ?it/s]

Procesando: electronics.video.tv

 25%|██▌       | 1/4 [00:40<02:01, 40.65s/it]

Procesando: computers.components.memory

 50%|█████     | 2/4 [00:42<00:36, 18.00s/it]

Procesando: computers.components.motherboard

 75%|███████▌  | 3/4 [00:46<00:11, 11.31s/it]

Procesando: appliances.kitchen.juicer

100%|██████████| 4/4 [01:00<00:00, 15.10s/it]

Resultados guardados en: drive/MyDrive/Master Data Science/TFM/GITHUB/processed/evaluation_201912/user_based_metrics.parquet

  0%|          | 0/4 [00:00<?, ?it/s]

Procesando: electronics.video.tv

 25%|██▌       | 1/4 [00:39<01:59, 39.97s/it]

Procesando: computers.components.memory

 50%|█████     | 2/4 [00:42<00:35, 17.75s/it]

Procesando: computers.components.motherboard

 75%|███████▌  | 3/4 [00:45<00:11, 11.16s/it]

Procesando: appliances.kitchen.juicer

100%|██████████| 4/4 [00:59<00:00, 14.89s/it]

Resultados guardados en: drive/MyDrive/Master Data Science/TFM/GITHUB/processed/evaluation_201912/time_based_metrics.parquet

In [11]:
general_metrics_dic

,category_code,visits,users,clicks,click_depth,dwell_time_avg,active_days,return_rate,dwelltime_l
0,electronics.video.tv,168605,104858,325528,1.930828,242.928133,1.317305,1.607936,390.613000
1,computers.components.memory,9062,5290,11454,1.263959,89.352350,1.345369,1.713043,153.064461
2,computers.components.motherboard,14294,11378,20132,1.408522,47.119070,1.146247,1.256284,59.194937
3,appliances.kitchen.juicer,59727,36292,92480,1.548586,213.331575,1.290339,1.645735,351.087154

In [12]:
user_based_metrics_dic

,category_code,Tourist_users,Tourist_visits,Interested_users,Interested_visits,Average_users,Average_visits,Active_users,Active_visits,VIP_users,...,Tourist_return_rate,Interested_return_rate,Average_return_rate,Active_return_rate,VIP_return_rate,Tourist_dwelltime_l,Interested_dwelltime_l,Average_dwelltime_l,Active_dwelltime_l,VIP_dwelltime_l
0,electronics.video.tv,85354.0,93474.0,17949.0,53190.0,1341.0,12080.0,192.0,4481.0,22.0,...,1.095133,2.963396,9.008203,23.338542,244.545455,107.061403,1262.212658,6160.544370,4015.807292,6045.409091
1,computers.components.memory,4263.0,4996.0,933.0,3021.0,81.0,773.0,13.0,272.0,0.0,...,1.171945,3.237942,9.543210,20.923077,0.000000,49.865353,470.988210,1263.518519,4258.307692,0.000000
2,computers.components.motherboard,10394.0,10895.0,899.0,2565.0,77.0,685.0,8.0,149.0,0.0,...,1.048201,2.853170,8.896104,18.625000,0.000000,32.978160,287.001112,801.441558,1377.500000,0.000000
3,appliances.kitchen.juicer,30369.0,35656.0,5392.0,17799.0,423.0,3920.0,96.0,1894.0,12.0,...,1.174092,3.301001,9.267139,19.729167,38.166667,75.871481,1352.361647,6663.257683,2529.843750,7013.083333

In [13]:
time_based_metrics_dic

,category_code,users,visits,clicks,click_depth,dwell_time_avg,return_rate,dwelltime_l
0,electronics.video.tv,0.685747,0.715474,0.713383,0.497675,0.525561,0.535393,0.560735
1,computers.components.memory,0.684444,0.702085,0.698708,0.496466,0.549277,0.520732,0.569724
2,computers.components.motherboard,0.713803,0.729817,0.725015,0.494701,0.538267,0.519931,0.558021
3,appliances.kitchen.juicer,0.689187,0.712117,0.708348,0.494386,0.501258,0.527314,0.528568